root = "."
tmp_dir = "tmp"

[build]
  # -gcflags "all=-N -l" disables optimizations and inlining for easier debugging
  cmd = "cd cmd/api-server && go build -race -gcflags \"all=-N -l\" -o /app/super-payment-kun ."
  bin = "./super-payment-kun"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "dlv --listen=:40001 --headless --continue --accept-multiclient --api-version=2 exec ./super-payment-kun"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
